### ISSUE TITLE
Erreur destination dossier

### ISSUE THREAD

**Issue by alain01** [GregMage/XoopsFrench#1]
Hello,
N'y aurait-il pas une erreur sur la version fr ?

On trouve : 
XoopsFrench-2\2.5.9\htdocs\class\tinymce\language\french.php

moi je l'aurai mis sous : 
XoopsFrench-2\2.5.9\htdocs\class\xoopseditor\tinymce\language\french.php

Non ?

**Comment by GregMage** [comment]
C'est juste! Bien vu.

https://github.com/GregMage/XoopsFrench/commit/7d92fe8cbf23609e5bfbaf104bf38e1a35ad9c1d

Erreur avec textarea aussi

**Comment by GregMage** [comment]
Nouvelle version disponible.

https://github.com/GregMage/XoopsFrench/releases/tag/V3
