### ISSUE TITLE
Erreur de traduction (installation module + blocs)

### ISSUE THREAD

**Issue by alain01** [GregMage/XoopsFrench#3]
1) Modules 
En bas, il faudrait pouvoir lire "Administration du module installé"
et non 
"Administration des modules"
puisque le lien emmène vers le module fraîchement installé 

![PM](https://user-images.githubusercontent.com/5336960/70433954-44786400-1a83-11ea-9322-8f1a4e5be01d.png)

2) Bloc
- Liste déroulante "Module"
il faudrait "Tout les modules" et non "Tout les types"

- Liste déroulante "page"
-- Il faudrait "Toutes les pages" et non "Tout les types"
-- Il faudrait "Page d'accueil" et non "Haut de la page"

- Liste déroulante "Visible"
Il faudrait "tout les états" au lieu de "Tout les types"

En espérant que la variable pour "Tout les types" est différente pour chaque liste...

**Comment by cesagonchu** [comment]
Pour répondre à alain01 :
1.
\modules\system\language\french\admin\modulesadmin.php
ligne 9
define('_AM_SYSTEM_MODULES_ADMIN', 'Administration des Modules');
remplacer par
define('_AM_SYSTEM_MODULES_ADMIN', 'Administration du module installé');

2.
\modules\system\language\french\admin\blocksadmin.php
ligne 16
define('_AM_SYSTEM_BLOCKS_TYPES', 'Tous les types');

Il n'y a malheureusement qu'une seule définition (define)

**Comment by GregMage** [comment]
Merci
