### ISSUE TITLE
Bug seulement en FR sur le publipostage, sur les dates

### ISSUE THREAD

**Issue by alain01** [GregMage/XoopsFrench#4]
Page /modules/system/admin.php?fct=mailusers

en anglais, aucun pb
en Fr,
Date (connexion / inscription)
Quand on clique sur un calendrier, le titre est "undefined, NaN"
et quand on valide, il affiche "NaN-NaN-NaN"

**Comment by GregMage** [comment]
Fix: https://github.com/XOOPS/XoopsCore25/pull/765
