### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by cesagonchu** [GregMage/XoopsFrench#5]
Frameworks\moduleclasses\moduleadmin\language\french\main.php

ajouter un espace après le mot « par » ligne 41 :

define('_AM_MODULEADMIN_ABOUT_BY', 'par ');

___
\modules\system\language\french\admin\modulesadmin.php
ligne 18
define('_AM_SYSTEM_MODULES_BTOMADMIN', 'Retour à page d\'administration des modules');
define('_AM_SYSTEM_MODULES_BTOMADMIN', 'Retour à la page d\'administration des modules');

___
\modules\system\language\french\admin\modulesadmin.php
ligne 19
define('_AM_SYSTEM_MODULES_INSTALLING', 'Installation');
define('_AM_SYSTEM_MODULES_INSTALLING', 'Installation de ');

**Comment by GregMage** [comment]
Merci!
